export const todoListTypes = {
  GET_TODO: 'GET_TODO',
  GET_TODO_LOADING: 'GET_TODO_LOADING',
  GET_TODO_ERROR_SHOW: 'GET_TODO_ERROR_SHOW',
  GET_TODO_ERROR_HIDE: 'GET_TODO_ERROR_HIDE',
  GET_TODO_CLEAR: 'GET_TODO_CLEAR',
};

export const todoDetailTypes = {
  GET_TODO_DETAIL: 'GET_TODO_DETAIL',
  GET_TODO_DETAIL_LOADING: 'GET_TODO_DETAIL_LOADING',
  GET_TODO_DETAIL_ERROR_SHOW: 'GET_TODO_DETAIL_ERROR_SHOW',
  GET_TODO_DETAIL_ERROR_HIDE: 'GET_TODO_DETAIL_ERROR_HIDE',
  GET_TODO_DETAIL_CLEAR: 'GET_TODO_DETAIL_CLEAR',
};
