export const todoListTypes = {
  GET_TODO: 'GET_TODO',
  GET_TODO_LOADING: 'GET_TODO_LOADING',
  GET_TODO_ERROR_SHOW: 'GET_TODO_ERROR_SHOW',
  GET_TODO_ERROR_HIDE: 'GET_TODO_ERROR_HIDE',
  GET_TODO_CLEAR: 'GET_TODO_CLEAR',
};
